[package]
name = "personal-website-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo = "0.11.0"
stylist = { version = "0.13.0", featues = ["yew_integration"], features = ["yew", "yew_integration"] }
yew = {version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
